# Generated by Django 4.2.4 on 2023-09-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_category_product_effect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
